-- Wellness Albania — Milestone 4 Wellness+ permissions (M4 Slice 2) on a live
-- MySQL database.
--
-- Gives the system roles of every existing workspace the nine Wellness+
-- permissions at their SRS M4 §10.2 defaults, once (FR-RBAC-26). A grant the
-- Administrator customised is never changed, and a key revoked after the
-- upgrade is never put back.
--
-- SAFE TO RUN ON PRODUCTION, AND SAFE TO RUN TWICE: the upgrade only touches
-- workspaces with no ledger row for it.
--
-- The same statements are also carried by mysql_upgrade_to_current.sql, which
-- is the file to run when bringing a database up to date generally. This one
-- exists for applying just this change on its own.
--
-- TAKE A BACKUP FIRST:
--   mysqldump -u USER -p --single-transaction --routines DBNAME > backup.sql

SELECT 'm4 wellness permissions' AS step, DATABASE() AS db, NOW() AS at;

-- BEGIN GENERATED PERMISSION UPGRADE m4-wellness-plus
-- Generated by scripts/generate-role-seed-sql.ts from PERMISSION_UPGRADES and DEFAULT_ROLE_MATRIX.
-- One Role audit entry per system role still missing one of its new keys, from
-- the system actor (FR-RBAC-10). Runs before the grants, which it describes.
INSERT INTO `AuditEntry` (`id`, `tenantId`, `at`, `userId`, `userRole`, `action`, `entityType`, `entityId`, `entityLabel`, `changes`)
SELECT UUID(), r.tenantId, NOW(3), NULL, 'SYSTEM', 'UPDATE', 'Role', r.id,
  COALESCE(NULLIF(r.nameSq, ''), r.nameEn), CAST(v.changes AS JSON)
FROM `Role` r
JOIN (
  SELECT 'RECEPTION' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["members.verify"]},{"field":"permissionUpgrade","old":null,"new":"m4-wellness-plus"}]' AS changes
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["members.import","members.manage","members.payments.record","members.payments.view","members.reports.view","members.verify","members.view","members.vip.approve","wellnessplus.settings.manage"]},{"field":"permissionUpgrade","old":null,"new":"m4-wellness-plus"}]' AS changes
  UNION ALL
  SELECT 'CEO' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["members.payments.view","members.reports.view","members.view"]},{"field":"permissionUpgrade","old":null,"new":"m4-wellness-plus"}]' AS changes
) v ON v.rolekey = r.`key`
WHERE r.isSystem = 1
  AND NOT EXISTS (
    SELECT 1 FROM `AppliedPermissionUpgrade` a WHERE a.tenantId = r.tenantId AND a.`key` = 'm4-wellness-plus'
  )
  AND EXISTS (
    SELECT 1 FROM (
  SELECT 'RECEPTION' AS rolekey, 'members.verify' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.import' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.manage' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.payments.record' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.payments.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.reports.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.verify' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.vip.approve' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'wellnessplus.settings.manage' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.payments.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.reports.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.view' AS permissionkey, NULL AS scope
    ) g
    WHERE g.rolekey = r.`key`
      AND NOT EXISTS (
        SELECT 1 FROM `RolePermission` rp WHERE rp.roleId = r.id AND rp.permissionKey = g.permissionkey
      )
  );

-- Grant the new keys to each system role at its default (SRS M2 §9.2). Never updates or deletes a grant.
INSERT INTO `RolePermission` (`roleId`, `permissionKey`, `scope`)
SELECT r.id, v.permissionkey, v.scope
FROM `Role` r
JOIN (
  SELECT 'RECEPTION' AS rolekey, 'members.verify' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.import' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.manage' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.payments.record' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.payments.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.reports.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.verify' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.vip.approve' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'wellnessplus.settings.manage' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.payments.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.reports.view' AS permissionkey, NULL AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.view' AS permissionkey, NULL AS scope
) v ON v.rolekey = r.`key`
WHERE r.isSystem = 1
  AND NOT EXISTS (
    SELECT 1 FROM `AppliedPermissionUpgrade` a WHERE a.tenantId = r.tenantId AND a.`key` = 'm4-wellness-plus'
  )
  AND NOT EXISTS (
    SELECT 1 FROM `RolePermission` rp WHERE rp.roleId = r.id AND rp.permissionKey = v.permissionkey
  );

-- Record the upgrade, so it never runs again for these tenants.
INSERT INTO `AppliedPermissionUpgrade` (`tenantId`, `key`, `appliedAt`)
SELECT t.id, 'm4-wellness-plus', NOW(3)
FROM `Tenant` t
WHERE NOT EXISTS (
    SELECT 1 FROM `AppliedPermissionUpgrade` a WHERE a.tenantId = t.id AND a.`key` = 'm4-wellness-plus'
  );
-- END GENERATED PERMISSION UPGRADE m4-wellness-plus

INSERT INTO `_prisma_migrations`
  (`id`, `checksum`, `finished_at`, `migration_name`, `logs`, `rolled_back_at`, `started_at`, `applied_steps_count`)
SELECT
  UUID(), '', NOW(3), '20261017100000_m4_wellness_permissions', NULL, NULL, NOW(3), 1
WHERE NOT EXISTS (
  SELECT 1 FROM `_prisma_migrations` WHERE `migration_name` = '20261017100000_m4_wellness_permissions'
);
