-- Wellness Albania — Milestone 3 contracts permission (M3 Slice 2) on a live
-- MySQL database.
--
-- Gives the system roles of every existing workspace "Contracts: suspend,
-- cancel, reinstate" (contracts.terminate) at its SRS §7.2 default, once
-- (FR-RBAC-20). A grant the Administrator customised is never changed, and a
-- key revoked after the upgrade is never put back.
--
-- SAFE TO RUN ON PRODUCTION, AND SAFE TO RUN TWICE: the upgrade only touches
-- workspaces with no ledger row for it.
--
-- The same statements are also carried by mysql_upgrade_to_current.sql, which
-- is the file to run when bringing a database up to date generally. This one
-- exists for applying just this change on its own.
--
-- TAKE A BACKUP FIRST:
--   mysqldump -u USER -p --single-transaction --routines DBNAME > backup.sql

SELECT 'm3 contracts permissions' AS step, DATABASE() AS db, NOW() AS at;

-- Give the system roles of every existing tenant the Milestone 3 contracts
-- permission (contracts.terminate) at its SRS M3 §7.2 default. Payment and
-- performance keys were seeded by Milestone 1. Customised grants are never
-- changed, copied roles are left to the Administrator, and the ledger row
-- makes it run once per tenant.
-- BEGIN GENERATED PERMISSION UPGRADE m3-contracts-payments
-- Generated by scripts/generate-role-seed-sql.ts from PERMISSION_UPGRADES and DEFAULT_ROLE_MATRIX.
-- One Role audit entry per system role still missing one of its new keys, from
-- the system actor (FR-RBAC-10). Runs before the grants, which it describes.
INSERT INTO `AuditEntry` (`id`, `tenantId`, `at`, `userId`, `userRole`, `action`, `entityType`, `entityId`, `entityLabel`, `changes`)
SELECT UUID(), r.tenantId, NOW(3), NULL, 'SYSTEM', 'UPDATE', 'Role', r.id,
  COALESCE(NULLIF(r.nameSq, ''), r.nameEn), CAST(v.changes AS JSON)
FROM `Role` r
JOIN (
  SELECT 'SALES_MANAGER' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["contracts.terminate"]},{"field":"permissionUpgrade","old":null,"new":"m3-contracts-payments"}]' AS changes
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["contracts.terminate"]},{"field":"permissionUpgrade","old":null,"new":"m3-contracts-payments"}]' AS changes
) v ON v.rolekey = r.`key`
WHERE r.isSystem = 1
  AND NOT EXISTS (
    SELECT 1 FROM `AppliedPermissionUpgrade` a WHERE a.tenantId = r.tenantId AND a.`key` = 'm3-contracts-payments'
  )
  AND EXISTS (
    SELECT 1 FROM (
  SELECT 'SALES_MANAGER' AS rolekey, 'contracts.terminate' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'contracts.terminate' AS permissionkey, 'ALL' AS scope
    ) g
    WHERE g.rolekey = r.`key`
      AND NOT EXISTS (
        SELECT 1 FROM `RolePermission` rp WHERE rp.roleId = r.id AND rp.permissionKey = g.permissionkey
      )
  );

-- Grant the new keys to each system role at its default (SRS M2 §9.2). Never updates or deletes a grant.
INSERT INTO `RolePermission` (`roleId`, `permissionKey`, `scope`)
SELECT r.id, v.permissionkey, v.scope
FROM `Role` r
JOIN (
  SELECT 'SALES_MANAGER' AS rolekey, 'contracts.terminate' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'contracts.terminate' AS permissionkey, 'ALL' AS scope
) v ON v.rolekey = r.`key`
WHERE r.isSystem = 1
  AND NOT EXISTS (
    SELECT 1 FROM `AppliedPermissionUpgrade` a WHERE a.tenantId = r.tenantId AND a.`key` = 'm3-contracts-payments'
  )
  AND NOT EXISTS (
    SELECT 1 FROM `RolePermission` rp WHERE rp.roleId = r.id AND rp.permissionKey = v.permissionkey
  );

-- Record the upgrade, so it never runs again for these tenants.
INSERT INTO `AppliedPermissionUpgrade` (`tenantId`, `key`, `appliedAt`)
SELECT t.id, 'm3-contracts-payments', NOW(3)
FROM `Tenant` t
WHERE NOT EXISTS (
    SELECT 1 FROM `AppliedPermissionUpgrade` a WHERE a.tenantId = t.id AND a.`key` = 'm3-contracts-payments'
  );
-- END GENERATED PERMISSION UPGRADE m3-contracts-payments

INSERT INTO `_prisma_migrations`
  (`id`, `checksum`, `finished_at`, `migration_name`, `logs`, `rolled_back_at`, `started_at`, `applied_steps_count`)
SELECT
  UUID(), '', NOW(3), '20261008100000_m3_contracts_permissions', NULL, NULL, NOW(3), 1
WHERE NOT EXISTS (
  SELECT 1 FROM `_prisma_migrations` WHERE `migration_name` = '20261008100000_m3_contracts_permissions'
);
