/**
 * Generates the "seed the five system roles" SQL block from
 * `DEFAULT_ROLE_MATRIX` (src/access/domain), so the migration SQL and the
 * in-code matrix can never drift apart — a change to the matrix and a
 * forgotten migration update would otherwise ship a tenant with the wrong
 * defaults with nothing to catch it.
 *
 * Both `generatePostgresRoleSeedSql` and `generateMysqlRoleSeedSql` are pure
 * functions, unit-tested (`tests/unit/access/generateRoleSeedSql.test.ts`)
 * against the literal blocks committed in:
 *   - prisma/migrations/20260927112507_add_roles_and_permissions/migration.sql
 *   - prisma/mysql_migration_add_roles_and_permissions.sql
 * between the `-- BEGIN GENERATED ROLE SEED` / `-- END GENERATED ROLE SEED`
 * markers. If the matrix changes, regenerate with:
 *   npx ts-node -r tsconfig-paths/register scripts/generate-role-seed-sql.ts
 * and paste the printed blocks back between the markers in both files.
 *
 * Every INSERT is guarded with `WHERE NOT EXISTS (...)`, which is what makes
 * the block idempotent: safe on a fresh database, safe re-run on one that
 * already has the roles, and — because it selects from the live `Tenant`
 * table rather than a fixed list of ids — it also seeds any tenant created
 * between when this migration was written and when it is deployed.
 */
import { DEFAULT_ROLE_MATRIX, PermissionGrant } from '../src/access/domain/DefaultRoleMatrix';
import { PermissionScope } from '../src/access/domain/PermissionScope';
import { RoleKey, SYSTEM_ROLE_NAMES } from '../src/access/domain/RoleKey';

const ROLE_KEYS = Object.values(RoleKey);

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function roleNameRows(): string {
  return ROLE_KEYS.map((roleKey) => {
    const names = SYSTEM_ROLE_NAMES[roleKey];
    return `  SELECT ${sqlString(roleKey)} AS rolekey, ${sqlString(names.nameSq)} AS namesq, ${sqlString(names.nameEn)} AS nameen`;
  }).join('\n  UNION ALL\n');
}

/** `(roleKey, permissionKey, scope)` triples, in a stable order, for every granted key. */
function grantRows(scopeLiteral: (grant: PermissionGrant) => string): string {
  const rows: string[] = [];
  for (const roleKey of ROLE_KEYS) {
    const grants = DEFAULT_ROLE_MATRIX[roleKey];
    for (const permissionKey of Object.keys(grants).sort()) {
      const grant = grants[permissionKey as keyof typeof grants] as PermissionGrant;
      rows.push(
        `  SELECT ${sqlString(roleKey)} AS rolekey, ${sqlString(permissionKey)} AS permissionkey, ${scopeLiteral(grant)} AS scope`
      );
    }
  }
  return rows.join('\n  UNION ALL\n');
}

export function generatePostgresRoleSeedSql(): string {
  const scopeLiteral = (grant: PermissionGrant) => (grant === true ? 'NULL::TEXT' : sqlString(grant as PermissionScope));

  return `-- BEGIN GENERATED ROLE SEED
-- Generated by scripts/generate-role-seed-sql.ts from DEFAULT_ROLE_MATRIX.
-- Seed the five system roles for every tenant that doesn't have them yet.
INSERT INTO "Role" ("id", "tenantId", "key", "nameSq", "nameEn", "isSystem", "updatedAt")
SELECT gen_random_uuid(), t."id", v."rolekey", v."namesq", v."nameen", true, CURRENT_TIMESTAMP
FROM "Tenant" t
CROSS JOIN (
${roleNameRows()}
) v
WHERE NOT EXISTS (
  SELECT 1 FROM "Role" r WHERE r."tenantId" = t."id" AND r."key" = v."rolekey"
);

-- Grant each system role its default permissions (SRS §4.2).
INSERT INTO "RolePermission" ("roleId", "permissionKey", "scope")
SELECT r."id", v."permissionkey", v."scope"
FROM "Role" r
CROSS JOIN (
${grantRows(scopeLiteral)}
) v
WHERE r."isSystem" = true
  AND r."key" = v."rolekey"
  AND NOT EXISTS (
    SELECT 1 FROM "RolePermission" rp WHERE rp."roleId" = r."id" AND rp."permissionKey" = v."permissionkey"
  );

-- D2: map every legacy user onto the new roles (BUSINESS_OWNER -> Administrator,
-- STAFF -> Sales User). SUPER_ADMIN is left alone: it has no tenant and no row here.
UPDATE "User" u
SET "roleId" = r."id"
FROM "Role" r
WHERE u."roleId" IS NULL
  AND r."isSystem" = true
  AND r."tenantId" = u."tenantId"
  AND (
    (u."role" = 'BUSINESS_OWNER' AND r."key" = 'ADMINISTRATOR')
    OR (u."role" = 'STAFF' AND r."key" = 'SALES_USER')
  );
-- END GENERATED ROLE SEED`;
}

export function generateMysqlRoleSeedSql(): string {
  const scopeLiteral = (grant: PermissionGrant) => (grant === true ? 'NULL' : sqlString(grant as PermissionScope));

  return `-- BEGIN GENERATED ROLE SEED
-- Generated by scripts/generate-role-seed-sql.ts from DEFAULT_ROLE_MATRIX.
-- Seed the five system roles for every tenant that doesn't have them yet.
INSERT INTO \`Role\` (\`id\`, \`tenantId\`, \`key\`, \`nameSq\`, \`nameEn\`, \`isSystem\`, \`updatedAt\`)
SELECT UUID(), t.id, v.rolekey, v.namesq, v.nameen, 1, NOW(3)
FROM \`Tenant\` t
JOIN (
${roleNameRows()}
) v ON 1 = 1
WHERE NOT EXISTS (
  SELECT 1 FROM \`Role\` r WHERE r.tenantId = t.id AND r.\`key\` = v.rolekey
);

-- Grant each system role its default permissions (SRS §4.2).
INSERT INTO \`RolePermission\` (\`roleId\`, \`permissionKey\`, \`scope\`)
SELECT r.id, v.permissionkey, v.scope
FROM \`Role\` r
JOIN (
${grantRows(scopeLiteral)}
) v ON v.rolekey = r.\`key\`
WHERE r.isSystem = 1
  AND NOT EXISTS (
    SELECT 1 FROM \`RolePermission\` rp WHERE rp.roleId = r.id AND rp.permissionKey = v.permissionkey
  );

-- D2: map every legacy user onto the new roles (BUSINESS_OWNER -> Administrator,
-- STAFF -> Sales User). SUPER_ADMIN is left alone: it has no tenant and no row here.
UPDATE \`User\` u
JOIN \`Role\` r ON r.tenantId = u.tenantId AND r.isSystem = 1
SET u.roleId = r.id
WHERE u.roleId IS NULL
  AND (
    (u.role = 'BUSINESS_OWNER' AND r.\`key\` = 'ADMINISTRATOR')
    OR (u.role = 'STAFF' AND r.\`key\` = 'SALES_USER')
  );
-- END GENERATED ROLE SEED`;
}

/* istanbul ignore next -- CLI entry point, exercised by hand, not by tests */
if (require.main === module) {
  process.stdout.write('===== Postgres (paste between the markers in the migration.sql) =====\n\n');
  process.stdout.write(generatePostgresRoleSeedSql());
  process.stdout.write('\n\n===== MySQL (paste between the markers in mysql_migration_add_roles_and_permissions.sql) =====\n\n');
  process.stdout.write(generateMysqlRoleSeedSql());
  process.stdout.write('\n');
}
