-- M3 Slice 2: the Milestone 3 contracts permission reaches every existing
-- workspace once (FR-RBAC-20). "Contracts: suspend, cancel, reinstate"
-- (contracts.terminate) is new; the payment and performance keys were seeded
-- by Milestone 1 and are only activated in the catalogue. Customised grants
-- are never changed, copied roles are left to the Administrator, and the
-- ledger row makes it run once per tenant.
-- BEGIN GENERATED PERMISSION UPGRADE m3-contracts-payments
-- Generated by scripts/generate-role-seed-sql.ts from PERMISSION_UPGRADES and DEFAULT_ROLE_MATRIX.
-- One Role audit entry per system role still missing one of its new keys, from
-- the system actor (FR-RBAC-10). Runs before the grants, which it describes.
INSERT INTO "AuditEntry" ("id", "tenantId", "at", "userId", "userRole", "action", "entityType", "entityId", "entityLabel", "changes")
SELECT gen_random_uuid(), r."tenantId", CURRENT_TIMESTAMP, NULL, 'SYSTEM', 'UPDATE', 'Role', r."id",
  COALESCE(NULLIF(r."nameSq", ''), r."nameEn"), v."changes"::jsonb
FROM "Role" r
CROSS JOIN (
  SELECT 'SALES_MANAGER' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["contracts.terminate"]},{"field":"permissionUpgrade","old":null,"new":"m3-contracts-payments"}]' AS changes
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["contracts.terminate"]},{"field":"permissionUpgrade","old":null,"new":"m3-contracts-payments"}]' AS changes
) v
WHERE r."isSystem" = true
  AND r."key" = v."rolekey"
  AND NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = r."tenantId" AND a."key" = 'm3-contracts-payments'
  )
  AND EXISTS (
    SELECT 1 FROM (
  SELECT 'SALES_MANAGER' AS rolekey, 'contracts.terminate' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'contracts.terminate' AS permissionkey, 'ALL' AS scope
    ) g
    WHERE g."rolekey" = r."key"
      AND NOT EXISTS (
        SELECT 1 FROM "RolePermission" rp WHERE rp."roleId" = r."id" AND rp."permissionKey" = g."permissionkey"
      )
  );

-- Grant the new keys to each system role at its default (SRS M2 §9.2). Never updates or deletes a grant.
INSERT INTO "RolePermission" ("roleId", "permissionKey", "scope")
SELECT r."id", v."permissionkey", v."scope"
FROM "Role" r
CROSS JOIN (
  SELECT 'SALES_MANAGER' AS rolekey, 'contracts.terminate' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'contracts.terminate' AS permissionkey, 'ALL' AS scope
) v
WHERE r."isSystem" = true
  AND r."key" = v."rolekey"
  AND NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = r."tenantId" AND a."key" = 'm3-contracts-payments'
  )
  AND NOT EXISTS (
    SELECT 1 FROM "RolePermission" rp WHERE rp."roleId" = r."id" AND rp."permissionKey" = v."permissionkey"
  );

-- Record the upgrade, so it never runs again for these tenants.
INSERT INTO "AppliedPermissionUpgrade" ("tenantId", "key", "appliedAt")
SELECT t."id", 'm3-contracts-payments', CURRENT_TIMESTAMP
FROM "Tenant" t
WHERE NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = t."id" AND a."key" = 'm3-contracts-payments'
  );
-- END GENERATED PERMISSION UPGRADE m3-contracts-payments
