import type { ReceiptLanguage } from '../application/receiptDocument';

/** Every label the receipt PDF prints, in Albanian and English (FR-MPAY-11, NFR-I18N-02). A test checks both carry the same keys. */
export const RECEIPT_LABELS = {
  sq: {
    title: 'Kupon pagese anëtarësie',
    receipt: 'Kupon pagese',
    receiptNumber: 'Nr. i kuponit',
    member: 'Anëtari',
    memberNumber: 'ID e anëtarit',
    tier: 'Niveli',
    kind: 'Lloji i pagesës',
    period: 'Periudha',
    listFee: 'Tarifa e listës',
    discount: 'Zbritja familjare',
    amount: 'Shuma e paguar',
    method: 'Mënyra e pagesës',
    receivedOn: 'Data e pranimit',
    agent: 'Pranuar nga',
    notAnInvoice: 'Ky është një kupon pagese, jo një faturë.',
    voided: 'ANULUAR',
    voidedOn: 'Anuluar më',
    voidReason: 'Arsyeja',
    page: 'Wellness+',
    NEW: 'Anëtarësim i ri',
    RENEWAL: 'Rinovim',
    UPGRADE: 'Përmirësim niveli',
    CASH: 'Para në dorë',
    BANK_TRANSFER: 'Transfertë bankare',
    CARD: 'Kartë',
    OTHER: 'Tjetër',
    BRONZE: 'Bronz',
    SILVER: 'Argjend',
    GOLD: 'Ar',
    VIP: 'VIP',
  },
  en: {
    title: 'Membership payment receipt',
    receipt: 'Receipt',
    receiptNumber: 'Receipt number',
    member: 'Member',
    memberNumber: 'Member ID',
    tier: 'Tier',
    kind: 'Payment kind',
    period: 'Period',
    listFee: 'List fee',
    discount: 'Family discount',
    amount: 'Amount paid',
    method: 'Method',
    receivedOn: 'Date received',
    agent: 'Received by',
    notAnInvoice: 'This is a receipt, not an invoice.',
    voided: 'VOIDED',
    voidedOn: 'Voided on',
    voidReason: 'Reason',
    page: 'Wellness+',
    NEW: 'New membership',
    RENEWAL: 'Renewal',
    UPGRADE: 'Upgrade',
    CASH: 'Cash',
    BANK_TRANSFER: 'Bank transfer',
    CARD: 'Card',
    OTHER: 'Other',
    BRONZE: 'Bronze',
    SILVER: 'Silver',
    GOLD: 'Gold',
    VIP: 'VIP',
  },
} as const;

export type ReceiptLabel = keyof (typeof RECEIPT_LABELS)['en'];

export const receiptLabel = (language: ReceiptLanguage, key: ReceiptLabel): string => RECEIPT_LABELS[language][key];
