-- M2 Slice 2: the Milestone 2 sales permissions reach every existing
-- workspace once (FR-RBAC-16, plan D7), and Tenant.salesWorkflow is added for
-- the later slices that key the sales process on it (plan D6).

-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "salesWorkflow" TEXT NOT NULL DEFAULT 'LEGACY_QUOTATIONS';

-- CreateTable
CREATE TABLE "AppliedPermissionUpgrade" (
    "tenantId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "appliedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AppliedPermissionUpgrade_pkey" PRIMARY KEY ("tenantId","key")
);

-- AddForeignKey
ALTER TABLE "AppliedPermissionUpgrade" ADD CONSTRAINT "AppliedPermissionUpgrade_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Give the system roles of every existing tenant the new keys at their SRS M2
-- §9.2 defaults. Customised grants are never changed, copied roles are left
-- to the Administrator, and the ledger row makes it run once per tenant.
-- BEGIN GENERATED PERMISSION UPGRADE m2-sales
-- Generated by scripts/generate-role-seed-sql.ts from PERMISSION_UPGRADES and DEFAULT_ROLE_MATRIX.
-- One Role audit entry per system role still missing one of its new keys, from
-- the system actor (FR-RBAC-10). Runs before the grants, which it describes.
INSERT INTO "AuditEntry" ("id", "tenantId", "at", "userId", "userRole", "action", "entityType", "entityId", "entityLabel", "changes")
SELECT gen_random_uuid(), r."tenantId", CURRENT_TIMESTAMP, NULL, 'SYSTEM', 'UPDATE', 'Role', r."id",
  COALESCE(NULLIF(r."nameSq", ''), r."nameEn"), v."changes"::jsonb
FROM "Role" r
CROSS JOIN (
  SELECT 'SALES_USER' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["deals.edit","deals.view","discounts.apply","followups.manage","offers.edit","script.view"]},{"field":"permissionUpgrade","old":null,"new":"m2-sales"}]' AS changes
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["deals.delete","deals.edit","deals.reopen","deals.view","discounts.apply","discounts.approve","followups.manage","offers.edit","script.view"]},{"field":"permissionUpgrade","old":null,"new":"m2-sales"}]' AS changes
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["activityResults.manage","deals.delete","deals.edit","deals.reopen","deals.view","discounts.apply","followups.manage","offers.edit","script.edit","script.view"]},{"field":"permissionUpgrade","old":null,"new":"m2-sales"}]' AS changes
  UNION ALL
  SELECT 'CEO' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["deals.view","discounts.approve","script.view"]},{"field":"permissionUpgrade","old":null,"new":"m2-sales"}]' AS changes
) v
WHERE r."isSystem" = true
  AND r."key" = v."rolekey"
  AND NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = r."tenantId" AND a."key" = 'm2-sales'
  )
  AND EXISTS (
    SELECT 1 FROM (
  SELECT 'SALES_USER' AS rolekey, 'deals.edit' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'deals.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'discounts.apply' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'followups.manage' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'offers.edit' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'script.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'deals.delete' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'deals.edit' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'deals.reopen' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'deals.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'discounts.apply' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'discounts.approve' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'followups.manage' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'offers.edit' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'script.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'activityResults.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'deals.delete' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'deals.edit' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'deals.reopen' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'deals.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'discounts.apply' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'followups.manage' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'offers.edit' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'script.edit' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'script.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'deals.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'discounts.approve' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'script.view' AS permissionkey, NULL::TEXT AS scope
    ) g
    WHERE g."rolekey" = r."key"
      AND NOT EXISTS (
        SELECT 1 FROM "RolePermission" rp WHERE rp."roleId" = r."id" AND rp."permissionKey" = g."permissionkey"
      )
  );

-- Grant the new keys to each system role at its default (SRS M2 §9.2). Never updates or deletes a grant.
INSERT INTO "RolePermission" ("roleId", "permissionKey", "scope")
SELECT r."id", v."permissionkey", v."scope"
FROM "Role" r
CROSS JOIN (
  SELECT 'SALES_USER' AS rolekey, 'deals.edit' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'deals.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'discounts.apply' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'followups.manage' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'offers.edit' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'script.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'deals.delete' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'deals.edit' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'deals.reopen' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'deals.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'discounts.apply' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'discounts.approve' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'followups.manage' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'offers.edit' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'script.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'activityResults.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'deals.delete' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'deals.edit' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'deals.reopen' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'deals.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'discounts.apply' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'followups.manage' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'offers.edit' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'script.edit' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'script.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'deals.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'discounts.approve' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'script.view' AS permissionkey, NULL::TEXT AS scope
) v
WHERE r."isSystem" = true
  AND r."key" = v."rolekey"
  AND NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = r."tenantId" AND a."key" = 'm2-sales'
  )
  AND NOT EXISTS (
    SELECT 1 FROM "RolePermission" rp WHERE rp."roleId" = r."id" AND rp."permissionKey" = v."permissionkey"
  );

-- Record the upgrade, so it never runs again for these tenants.
INSERT INTO "AppliedPermissionUpgrade" ("tenantId", "key", "appliedAt")
SELECT t."id", 'm2-sales', CURRENT_TIMESTAMP
FROM "Tenant" t
WHERE NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = t."id" AND a."key" = 'm2-sales'
  );
-- END GENERATED PERMISSION UPGRADE m2-sales
