import { OfferLanguage } from '../../domain/Offer';

/**
 * Every label the offer PDF prints, in Albanian and English (NFR-I18N-02,
 * FR-OFR-06). Server-side, since the PDF is drawn on the server; a test
 * checks both languages carry the same keys. `{name}` placeholders are filled
 * by `label()`.
 */
const LABELS = {
  sq: {
    title: 'Ofertë',
    number: 'Nr. i ofertës',
    date: 'Data',
    validUntil: 'E vlefshme deri më',
    validFor: 'E vlefshme {days} ditë nga data e dërgimit',
    preparedFor: 'Për',
    nipt: 'NIPT',
    address: 'Adresa',
    contact: 'Personi i kontaktit',
    phone: 'Tel.',
    email: 'Email',
    website: 'Web',
    details: 'Të dhënat e ofertës',
    employees: 'Numri i punonjësve',
    businessType: 'Lloji i biznesit',
    riskLevel: 'Niveli i riskut',
    zone: 'Zona',
    frequency: 'Frekuenca e vizitave',
    package: 'Paketa e shërbimit',
    services: 'Shërbimet e përfshira',
    price: 'Çmimi',
    baseFee: 'Tarifa bazë',
    riskFee: 'Shtesa për riskun',
    visitFee: 'Shtesa për vizitat',
    locationFee: 'Shtesa për vendndodhjen',
    listPrice: 'Çmimi i listës në muaj',
    discount: 'Zbritja ({percent}%)',
    netMonthlyPrice: 'Çmimi neto në muaj',
    annualValue: 'Vlera vjetore ({months} muaj)',
    vatNote: 'Çmimet nuk përfshijnë TVSH-në.',
    priceOnRequest: 'Çmimi sipas kërkesës: do t’ju njoftojmë çmimin veçmas.',
    note: 'Shënim',
    salesperson: 'Përfaqësuesi i shitjeve',
    bankDetails: 'Të dhënat bankare',
    page: 'Faqe {page} nga {pages}',
    watermark: 'DRAFT – PROJEKT',
    commercialProposal: 'Propozim Komercial',
    proposalSubtitle: 'Shëndeti në Punë & Mirëqenia e Punonjësve',
    proposalTagline: 'Zgjidhje të përshtatura për një vend pune më të shëndetshëm, më të sigurt dhe më produktiv',
    proposalInfo: 'INFORMACIONI I OFERTËS',
    proposalNo: 'Nr. i Propozimit:',
    workLocations: 'Vendndodhjet e Punës',
    preparedBy: 'Përgatitur Nga',
    proposedSolution: 'ZGJIDHJA JONË E PROPOZUAR',
    solutionTitle: 'Shëndeti në Punë + Wellness+ Silver',
    solutionSubtitle: 'Një zgjidhje e plotë që kombinon pajtueshmërinë ligjore me përfitime të zgjeruara për punonjësit.',
    employeeBenefitsTitle: 'PËRFITIMET E PUNONJËSVE - WELLNESS+ SILVER',
    employeeBenefitsIntro:
      'Si pjesë e marrëveshjes së shëndetit në punë, punonjësit e kualifikuar do të kenë qasje në paketën Wellness+ Silver, duke ofruar qasje preferenciale në një gamë të gjerë shërbimesh shëndetësore dhe mirëqenieje në Klinikën Wellness Albania.',
    serviceHeader: 'Shërbimi',
    benefitHeader: 'Përfitimi Wellness+ Silver',
    commercialOfferTitle: 'OFERTA KOMERCIALE',
    descriptionHeader: 'Përshkrimi',
    quantityHeader: 'Sasia',
    unitPriceHeader: 'Çmimi për Njësi',
    totalHeader: 'Totali',
    occHealthServices: 'Shërbimet e Shëndetit në Punë',
    medExamPackage: 'Paketa e Ekzaminimit Mjekësor',
    occDoctorVisits: 'Mjeku i Punës / Vizita në Vendin e Punës',
    silverBenefitsRow: 'Përfitimet e Punonjësve Wellness+ Silver',
    additionalServices: 'Shërbime Shtesë',
    included: 'E përfshirë',
    total: 'TOTALI',
    commercialConditionsTitle: 'KUSHTET KOMERCIALE',
    agreementDuration: 'Kohëzgjatja e marrëveshjes:',
    months12: '12 muaj',
    startDate: 'Data e fillimit:',
    expiryDate: 'Data e skadimit:',
    proposalValidity: 'Vlefshmëria e propozimit:',
    days30: '30 ditë',
    paymentTerms: 'Kushtet e pagesës:',
    vat: 'TVSH:',
    asApplicable: 'Sipas ligjit në fuqi',
    contractClause:
      'Marrëveshja ndërmjet {company} dhe subjektit kontraktor do të jetë e vlefshme për një periudhë prej një (1) viti nga data efektive e fillimit, përveç rasteve kur është rënë dakord ndryshe me shkrim.',
    footerTagline: 'Punonjës më të Shëndetshëm · Biznese më të Forta',
    p2Title: 'Shërbimi i Shëndetit në Punë',
    p2Subtitle: 'Mbështetje e plotë për kompaninë dhe punonjësit tuaj',
    p2Tagline: 'Pajtueshmëri e qartë. Kujdes më i mirë për punonjësit. Më pak barrë administrative.',
    p2PartnerTitle: 'NJË PARTNER PËR NEVOJAT TUAJA TË SHËNDETIT NË PUNË',
    p2PartnerText:
      'Wellness Albania menaxhon aktivitetet mjekësore, administrative dhe të pajtueshmërisë të kërkuara për shëndetin në punë, ndërsa u jep punonjësve qasje të drejtpërdrejtë në mbështetje mjekësore profesionale.',
    card1Title: 'KUJDESI MJEKËSOR & MBËSHTETJA E PUNONJËSVE',
    card2Title: 'MONITORIMI I SHËNDETIT TË PUNONJËSVE',
    card3Title: 'MBËSHTETJE PËR LEJEN E LINDJES & LEJET MJEKËSORE',
    card4Title: 'PARANDALIMI I RISKUT NË VENDIN E PUNËS',
    card5Title: 'AKSIDENTET & SËMUNDJET PROFESIONALE',
    card6Title: 'PAJTUESHMËRIA LIGJORE & RAPORTIMI',
    val1: 'Pajtueshmëri ligjore e thjeshtuar',
    val2: 'Administrim i reduktuar i HR',
    val3: 'Menaxhim i strukturuar i riskut',
    val4: 'Qasje e drejtpërdrejtë mjekësore',
    val5: 'Raportim dhe ndjekje e rregullt',
  },
  en: {
    title: 'Offer',
    number: 'Offer no.',
    date: 'Date',
    validUntil: 'Valid until',
    validFor: 'Valid for {days} days from the date sent',
    preparedFor: 'Prepared for',
    nipt: 'NIPT',
    address: 'Address',
    contact: 'Contact person',
    phone: 'Phone',
    email: 'Email',
    website: 'Web',
    details: 'Offer details',
    employees: 'Number of employees',
    businessType: 'Business type',
    riskLevel: 'Risk level',
    zone: 'Zone',
    frequency: 'Visit frequency',
    package: 'Service package',
    services: 'Services included',
    price: 'Price',
    baseFee: 'Base fee',
    riskFee: 'Risk surcharge',
    visitFee: 'Visit surcharge',
    locationFee: 'Location surcharge',
    listPrice: 'List price per month',
    discount: 'Discount ({percent}%)',
    netMonthlyPrice: 'Net monthly price',
    annualValue: 'Annual value ({months} months)',
    vatNote: 'Prices do not include VAT.',
    priceOnRequest: 'Price on request: we will let you know the price separately.',
    note: 'Note',
    salesperson: 'Sales representative',
    bankDetails: 'Bank details',
    page: 'Page {page} of {pages}',
    watermark: 'DRAFT',
    commercialProposal: 'Commercial Proposal',
    proposalSubtitle: 'Occupational Health & Employee Wellness',
    proposalTagline: 'Tailored solutions for a healthier, safer and more productive workplace',
    proposalInfo: 'PROPOSAL INFORMATION',
    proposalNo: 'Proposal No.:',
    workLocations: 'Work Locations',
    preparedBy: 'Prepared By',
    proposedSolution: 'OUR PROPOSED SOLUTION',
    solutionTitle: 'Occupational Health + Wellness+ Silver',
    solutionSubtitle: 'A complete solution combining legal compliance with enhanced employee benefits.',
    employeeBenefitsTitle: 'EMPLOYEE BENEFITS - WELLNESS+ SILVER',
    employeeBenefitsIntro:
      'As part of the occupational health agreement, eligible employees will receive access to the Wellness+ Silver package, offering preferential access to a wide range of healthcare and wellness services at Wellness Albania Clinic.',
    serviceHeader: 'Service',
    benefitHeader: 'Wellness+ Silver Benefit',
    commercialOfferTitle: 'COMMERCIAL OFFER',
    descriptionHeader: 'Description',
    quantityHeader: 'Quantity',
    unitPriceHeader: 'Unit Price',
    totalHeader: 'Total',
    occHealthServices: 'Occupational Health Services',
    medExamPackage: 'Medical Examination Package',
    occDoctorVisits: 'Occupational Doctor / Workplace Visits',
    silverBenefitsRow: 'Wellness+ Silver Employee Benefits',
    additionalServices: 'Additional Services (if applicable)',
    included: 'Included',
    total: 'TOTAL',
    commercialConditionsTitle: 'COMMERCIAL CONDITIONS',
    agreementDuration: 'Agreement duration:',
    months12: '12 months',
    startDate: 'Start date:',
    expiryDate: 'Expiry date:',
    proposalValidity: 'Proposal validity:',
    days30: '30 days',
    paymentTerms: 'Payment terms:',
    vat: 'VAT:',
    asApplicable: 'As applicable',
    contractClause:
      'The agreement between {company} and the contracting entity will be valid for a period of one (1) year from the effective start date, unless otherwise agreed in writing.',
    footerTagline: 'Healthier Employees · Stronger Businesses',
    p2Title: 'Occupational Health Service',
    p2Subtitle: 'Complete support for your company and your employees',
    p2Tagline: 'Clear compliance. Better employee care. Less administrative burden.',
    p2PartnerTitle: 'ONE PARTNER FOR YOUR OCCUPATIONAL HEALTH NEEDS',
    p2PartnerText:
      'Wellness Albania manages the medical, administrative and compliance activities required for occupational health, while giving employees direct access to professional medical support.',
    card1Title: 'MEDICAL CARE & EMPLOYEE SUPPORT',
    card2Title: 'EMPLOYEE HEALTH MONITORING',
    card3Title: 'MATERNITY & MEDICAL LEAVE SUPPORT',
    card4Title: 'WORKPLACE RISK PREVENTION',
    card5Title: 'ACCIDENTS & OCCUPATIONAL DISEASES',
    card6Title: 'LEGAL COMPLIANCE & REPORTING',
    val1: 'Simplified legal compliance',
    val2: 'Reduced HR administration',
    val3: 'Structured risk management',
    val4: 'Direct medical access',
    val5: 'Regular reporting & follow-up',
  },
} as const satisfies Record<OfferLanguage, Record<string, string>>;

export type OfferPdfLabel = keyof (typeof LABELS)['sq'];

export const OFFER_PDF_LABELS: Record<OfferLanguage, Record<OfferPdfLabel, string>> = LABELS;

export function label(language: OfferLanguage, key: OfferPdfLabel, params: Record<string, string | number> = {}): string {
  return OFFER_PDF_LABELS[language][key].replace(/\{(\w+)\}/g, (_, name: string) => String(params[name] ?? ''));
}

