-- M4 Slice 2: the nine Wellness+ permissions reach every existing workspace
-- once (FR-RBAC-25, FR-RBAC-26). The Administrator receives all nine, the
-- Reception role "Members: verify". Customised grants are never changed, a
-- key is only inserted when missing, copied roles are left to the
-- Administrator, and the ledger row makes it run once per tenant.
-- BEGIN GENERATED PERMISSION UPGRADE m4-wellness-plus
-- Generated by scripts/generate-role-seed-sql.ts from PERMISSION_UPGRADES and DEFAULT_ROLE_MATRIX.
-- One Role audit entry per system role still missing one of its new keys, from
-- the system actor (FR-RBAC-10). Runs before the grants, which it describes.
INSERT INTO "AuditEntry" ("id", "tenantId", "at", "userId", "userRole", "action", "entityType", "entityId", "entityLabel", "changes")
SELECT gen_random_uuid(), r."tenantId", CURRENT_TIMESTAMP, NULL, 'SYSTEM', 'UPDATE', 'Role', r."id",
  COALESCE(NULLIF(r."nameSq", ''), r."nameEn"), v."changes"::jsonb
FROM "Role" r
CROSS JOIN (
  SELECT 'RECEPTION' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["members.verify"]},{"field":"permissionUpgrade","old":null,"new":"m4-wellness-plus"}]' AS changes
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["members.import","members.manage","members.payments.record","members.payments.view","members.reports.view","members.verify","members.view","members.vip.approve","wellnessplus.settings.manage"]},{"field":"permissionUpgrade","old":null,"new":"m4-wellness-plus"}]' AS changes
  UNION ALL
  SELECT 'CEO' AS rolekey, '[{"field":"permissionsAdded","old":null,"new":["members.payments.view","members.reports.view","members.view"]},{"field":"permissionUpgrade","old":null,"new":"m4-wellness-plus"}]' AS changes
) v
WHERE r."isSystem" = true
  AND r."key" = v."rolekey"
  AND NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = r."tenantId" AND a."key" = 'm4-wellness-plus'
  )
  AND EXISTS (
    SELECT 1 FROM (
  SELECT 'RECEPTION' AS rolekey, 'members.verify' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.import' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.payments.record' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.payments.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.reports.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.verify' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.vip.approve' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'wellnessplus.settings.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.payments.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.reports.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.view' AS permissionkey, NULL::TEXT AS scope
    ) g
    WHERE g."rolekey" = r."key"
      AND NOT EXISTS (
        SELECT 1 FROM "RolePermission" rp WHERE rp."roleId" = r."id" AND rp."permissionKey" = g."permissionkey"
      )
  );

-- Grant the new keys to each system role at its default (SRS M2 §9.2). Never updates or deletes a grant.
INSERT INTO "RolePermission" ("roleId", "permissionKey", "scope")
SELECT r."id", v."permissionkey", v."scope"
FROM "Role" r
CROSS JOIN (
  SELECT 'RECEPTION' AS rolekey, 'members.verify' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.import' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.payments.record' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.payments.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.reports.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.verify' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'members.vip.approve' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'wellnessplus.settings.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.payments.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.reports.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'members.view' AS permissionkey, NULL::TEXT AS scope
) v
WHERE r."isSystem" = true
  AND r."key" = v."rolekey"
  AND NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = r."tenantId" AND a."key" = 'm4-wellness-plus'
  )
  AND NOT EXISTS (
    SELECT 1 FROM "RolePermission" rp WHERE rp."roleId" = r."id" AND rp."permissionKey" = v."permissionkey"
  );

-- Record the upgrade, so it never runs again for these tenants.
INSERT INTO "AppliedPermissionUpgrade" ("tenantId", "key", "appliedAt")
SELECT t."id", 'm4-wellness-plus', CURRENT_TIMESTAMP
FROM "Tenant" t
WHERE NOT EXISTS (
    SELECT 1 FROM "AppliedPermissionUpgrade" a WHERE a."tenantId" = t."id" AND a."key" = 'm4-wellness-plus'
  );
-- END GENERATED PERMISSION UPGRADE m4-wellness-plus
