-- Slice 5 (FR-USR-02): an invitation carries the role the account is created with.
ALTER TABLE "Invitation" ADD COLUMN     "roleId" TEXT;

CREATE INDEX "Invitation_roleId_idx" ON "Invitation"("roleId");

ALTER TABLE "Invitation" ADD CONSTRAINT "Invitation_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Tenants created after 20260927112507_add_roles_and_permissions ran (the
-- Wellness workspace among them, when it was provisioned afterwards) have no
-- roles yet. The seed is idempotent, so running it again only fills that gap.
-- BEGIN GENERATED ROLE SEED
-- Generated by scripts/generate-role-seed-sql.ts from DEFAULT_ROLE_MATRIX.
-- Seed the five system roles for every tenant that doesn't have them yet.
INSERT INTO "Role" ("id", "tenantId", "key", "nameSq", "nameEn", "isSystem", "updatedAt")
SELECT gen_random_uuid(), t."id", v."rolekey", v."namesq", v."nameen", true, CURRENT_TIMESTAMP
FROM "Tenant" t
CROSS JOIN (
  SELECT 'SALES_USER' AS rolekey, 'Përdorues Shitjesh' AS namesq, 'Sales User' AS nameen
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'Menaxher Shitjesh' AS namesq, 'Sales Manager' AS nameen
  UNION ALL
  SELECT 'RECEPTION' AS rolekey, 'Recepsion' AS namesq, 'Reception' AS nameen
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'Administrator' AS namesq, 'Administrator' AS nameen
  UNION ALL
  SELECT 'CEO' AS rolekey, 'CEO' AS namesq, 'CEO' AS nameen
) v
WHERE NOT EXISTS (
  SELECT 1 FROM "Role" r WHERE r."tenantId" = t."id" AND r."key" = v."rolekey"
);

-- Grant each system role its default permissions (SRS §4.2).
INSERT INTO "RolePermission" ("roleId", "permissionKey", "scope")
SELECT r."id", v."permissionkey", v."scope"
FROM "Role" r
CROSS JOIN (
  SELECT 'SALES_USER' AS rolekey, 'activities.add' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'activities.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'calendar.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'commercial.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'companies.edit' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'companies.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'contracts.manage' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'contracts.validity.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'inventory.manage' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'invoices.manage' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'notes.add' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'notes.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'payments.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'performance.view' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_USER' AS rolekey, 'quotations.manage' AS permissionkey, 'OWN' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'activities.add' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'activities.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'calendar.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'commercial.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'companies.delete' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'companies.edit' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'companies.reassign' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'companies.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'contracts.manage' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'contracts.validity.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'invoices.manage' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'notes.add' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'notes.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'payments.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'performance.view' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'SALES_MANAGER' AS rolekey, 'quotations.manage' AS permissionkey, 'TEAM' AS scope
  UNION ALL
  SELECT 'RECEPTION' AS rolekey, 'companies.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'RECEPTION' AS rolekey, 'contracts.validity.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'RECEPTION' AS rolekey, 'notes.add' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'RECEPTION' AS rolekey, 'notes.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'activities.add' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'activities.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'audit.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'calendar.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'commercial.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'companies.delete' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'companies.edit' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'companies.reassign' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'companies.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'contracts.manage' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'contracts.validity.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'forms.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'integrations.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'inventory.manage' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'invoices.manage' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'notes.add' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'notes.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'payments.update' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'payments.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'pricing.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'quotations.approve' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'quotations.manage' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'reports.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'roles.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'settings.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'ADMINISTRATOR' AS rolekey, 'users.manage' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'activities.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'audit.view' AS permissionkey, NULL::TEXT AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'calendar.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'commercial.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'companies.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'contracts.validity.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'notes.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'payments.view' AS permissionkey, 'ALL' AS scope
  UNION ALL
  SELECT 'CEO' AS rolekey, 'performance.view' AS permissionkey, 'ALL' AS scope
) v
WHERE r."isSystem" = true
  AND r."key" = v."rolekey"
  AND NOT EXISTS (
    SELECT 1 FROM "RolePermission" rp WHERE rp."roleId" = r."id" AND rp."permissionKey" = v."permissionkey"
  );

-- D2: map every legacy user onto the new roles (BUSINESS_OWNER -> Administrator,
-- STAFF -> Sales User). SUPER_ADMIN is left alone: it has no tenant and no row here.
UPDATE "User" u
SET "roleId" = r."id"
FROM "Role" r
WHERE u."roleId" IS NULL
  AND r."isSystem" = true
  AND r."tenantId" = u."tenantId"
  AND (
    (u."role" = 'BUSINESS_OWNER' AND r."key" = 'ADMINISTRATOR')
    OR (u."role" = 'STAFF' AND r."key" = 'SALES_USER')
  );
-- END GENERATED ROLE SEED

-- D2 for open invitations: BUSINESS_OWNER -> Administrator, STAFF -> Sales User.
UPDATE "Invitation" i
SET "roleId" = r."id"
FROM "Role" r
WHERE i."roleId" IS NULL
  AND i."tenantId" IS NOT NULL
  AND r."isSystem" = true
  AND r."tenantId" = i."tenantId"
  AND (
    (i."role" = 'BUSINESS_OWNER' AND r."key" = 'ADMINISTRATOR')
    OR (i."role" = 'STAFF' AND r."key" = 'SALES_USER')
  );
